### ISSUE TITLE
Funnels in pushpop?

### ISSUE THREAD

**Issue by wetzler** [pushpop-project/pushpop#6]
Hi there! I am trying to get a funnel to run in pushpop and can't figure out the error. Here's my code.

```
  keen 'new_orgs' do
    analysis_type     'funnel'
    timeframe         timeframe
    steps [
      { # step 1 total new orgs
        actor_property: "organization.id",
        event_collection: "create_organization"  
      },
      { # step 2 heroku orgs
        actor_property: "organization.id", 
        event_collection: "create_organization",
        filters: [
          {
            property_name:"organization.name",
            operator:"contains",
            property_value:"@heroku.com"  
          }   
        ] 
      }
    ]
  end
```

I get the error: 

```
/Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/keen-0.8.7/lib/keen/client/querying_methods.rb:237:in `dup': can't dup NilClass (TypeError)
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/keen-0.8.7/lib/keen/client/querying_methods.rb:237:in `_query_url'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/keen-0.8.7/lib/keen/client/querying_methods.rb:223:in `query'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/keen-0.8.7/lib/keen/client/querying_methods.rb:176:in `funnel'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-keen-0.1.1/lib/pushpop-keen.rb:24:in `run'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop/job.rb:66:in `block in run'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop/job.rb:63:in `each'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop/job.rb:63:in `run'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop.rb:26:in `map'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop.rb:26:in `run'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/lib/pushpop/cli.rb:42:in `run_jobs_once'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/gems/pushpop-0.1.2/bin/pushpop:8:in `<top (required)>'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/bin/pushpop:23:in `load'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/bin/pushpop:23:in `<main>'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michellewetzler/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried it with & without filters but can't seem to get the funnel to execute at all.

**Comment by josephwegner** [comment]
@wetzler I fixed the bug that was causing your second issue. The new gem version should be pushed out shortly.

However, I could not recreate the issue you were having from the first code block you posted. It's possible the fix I did solved that as well, but I don't see why they should have been related - if the issue persists for you please reopen this ticket.
